if [ "$#" -ne 12 ]; then
  echo "Set DISTANCE_THRESHOLD, TIME_THRESHOLD, COSMOS_FILE, and date range arguments." >&2
  exit 1
fi

DISTANCE_THRESHOLD=$1
TIME_THRESHOLD=$2
COSMOS_FILE=$3
YEAR_START=$4
MONTH_START=$5
DAY_START=$6
YEAR_END=$7
MONTH_END=$8
DAY_END=$9
MIN_TWEET_COUNT=${10}
MAX_SAMPLE_TWEETS=${11}
MIN_DEGREE=${12}

#python -OO coupling.py $COSMOS_FILE $YEAR_START $MONTH_START $DAY_START $YEAR_END $MONTH_END $DAY_END 0 0 MIN_DISTINCT_LOCATIONS 2 $DISTANCE_THRESHOLD $TIME_THRESHOLD $MIN_TWEET_COUNT &&\

echo "start call_phast_${COSMOS_FILE:5:-4}_${DISTANCE_THRESHOLD}m_${TIME_THRESHOLD}h_${MAX_SAMPLE_TWEETS}-sample_${MIN_DEGREE}-degree.bat" >> call_phast_for_last_experiment.bat

python -OO routing.py  $COSMOS_FILE $DISTANCE_THRESHOLD $TIME_THRESHOLD $MAX_SAMPLE_TWEETS $MIN_DEGREE
